apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}-frontend
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
      tier: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend/frontend-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}-frontend
        tier: frontend
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  tier: frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        volumeMounts:
        - name: frontend-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: frontend-content
        configMap:
          name: {{ .Release.Name }}-frontend-content
          items:
          - key: index.html
            path: index.html
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-frontend-content
          items:
          - key: nginx.conf
            path: default.conf
