{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-backend-pdb
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
      tier: backend
{{- end }}
