apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
    tier: backend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
      tier: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
