{
 "title": "Guestbook dashboard",
 "time": { "from": "2025-12-04T12:03:31.200Z", "to": "2025-12-04T14:03:31.200Z" },
 "panels": [
  {
   "title": "Button Clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"backend\"} | json | event=\"button_clicked\" [1m]))"
    }
   ]
  },
  {
   "title": "Counter Incremented Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"backend\"} | json | event=\"button_clicked\""
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(guestbook_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counter Value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(guestbook_counter_value)", "legendFormat": "__auto" }
   ]
  }
 ]
}